# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vokabel', '0008_auto_20160203_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conjugation',
            old_name='futurePl1',
            new_name='pl1',
        ),
        migrations.RenameField(
            model_name='conjugation',
            old_name='futurePl2',
            new_name='pl2',
        ),
        migrations.RenameField(
            model_name='conjugation',
            old_name='futurePl3',
            new_name='pl3',
        ),
        migrations.RenameField(
            model_name='conjugation',
            old_name='futureSg1',
            new_name='sg1',
        ),
        migrations.RenameField(
            model_name='conjugation',
            old_name='futureSg2',
            new_name='sg2',
        ),
        migrations.RenameField(
            model_name='conjugation',
            old_name='futureSg3',
            new_name='sg3',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='imperfectPl1',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='imperfectPl2',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='imperfectPl3',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='imperfectSg1',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='imperfectSg2',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='imperfectSg3',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='perfectPl1',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='perfectPl2',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='perfectPl3',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='perfectSg1',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='perfectSg2',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='perfectSg3',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='pluqperfPl1',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='pluqperfPl2',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='pluqperfPl3',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='pluqperfSg1',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='pluqperfSg2',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='pluqperfSg3',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='presentPl1',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='presentPl2',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='presentPl3',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='presentSg1',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='presentSg2',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='presentSg3',
        ),
    ]
