# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vokabel', '0013_auto_20160206_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('translation', models.CharField(max_length=100)),
                ('posSg1m', models.CharField(max_length=100)),
                ('posSg2m', models.CharField(max_length=100)),
                ('posSg3m', models.CharField(max_length=100)),
                ('posSg4m', models.CharField(max_length=100)),
                ('posSg5m', models.CharField(max_length=100)),
                ('posSg6m', models.CharField(max_length=100)),
                ('posPl1m', models.CharField(max_length=100)),
                ('posPl2m', models.CharField(max_length=100)),
                ('posPl3m', models.CharField(max_length=100)),
                ('posPl4m', models.CharField(max_length=100)),
                ('posPl5m', models.CharField(max_length=100)),
                ('posPl6m', models.CharField(max_length=100)),
                ('posSg1f', models.CharField(max_length=100)),
                ('posSg2f', models.CharField(max_length=100)),
                ('posSg3f', models.CharField(max_length=100)),
                ('posSg4f', models.CharField(max_length=100)),
                ('posSg5f', models.CharField(max_length=100)),
                ('posSg6f', models.CharField(max_length=100)),
                ('posPl1f', models.CharField(max_length=100)),
                ('posPl2f', models.CharField(max_length=100)),
                ('posPl3f', models.CharField(max_length=100)),
                ('posPl4f', models.CharField(max_length=100)),
                ('posPl5f', models.CharField(max_length=100)),
                ('posPl6f', models.CharField(max_length=100)),
                ('posSg1n', models.CharField(max_length=100)),
                ('posSg2n', models.CharField(max_length=100)),
                ('posSg3n', models.CharField(max_length=100)),
                ('posSg4n', models.CharField(max_length=100)),
                ('posSg5n', models.CharField(max_length=100)),
                ('posSg6n', models.CharField(max_length=100)),
                ('posPl1n', models.CharField(max_length=100)),
                ('posPl2n', models.CharField(max_length=100)),
                ('posPl3n', models.CharField(max_length=100)),
                ('posPl4n', models.CharField(max_length=100)),
                ('posPl5n', models.CharField(max_length=100)),
                ('posPl6n', models.CharField(max_length=100)),
                ('compSg1m', models.CharField(max_length=100)),
                ('compSg2m', models.CharField(max_length=100)),
                ('compSg3m', models.CharField(max_length=100)),
                ('compSg4m', models.CharField(max_length=100)),
                ('compSg5m', models.CharField(max_length=100)),
                ('compSg6m', models.CharField(max_length=100)),
                ('compPl1m', models.CharField(max_length=100)),
                ('compPl2m', models.CharField(max_length=100)),
                ('compPl3m', models.CharField(max_length=100)),
                ('compPl4m', models.CharField(max_length=100)),
                ('compPl5m', models.CharField(max_length=100)),
                ('compPl6m', models.CharField(max_length=100)),
                ('compSg1f', models.CharField(max_length=100)),
                ('compSg2f', models.CharField(max_length=100)),
                ('compSg3f', models.CharField(max_length=100)),
                ('compSg4f', models.CharField(max_length=100)),
                ('compSg5f', models.CharField(max_length=100)),
                ('compSg6f', models.CharField(max_length=100)),
                ('compPl1f', models.CharField(max_length=100)),
                ('compPl2f', models.CharField(max_length=100)),
                ('compPl3f', models.CharField(max_length=100)),
                ('compPl4f', models.CharField(max_length=100)),
                ('compPl5f', models.CharField(max_length=100)),
                ('compPl6f', models.CharField(max_length=100)),
                ('compSg1n', models.CharField(max_length=100)),
                ('compSg2n', models.CharField(max_length=100)),
                ('compSg3n', models.CharField(max_length=100)),
                ('compSg4n', models.CharField(max_length=100)),
                ('compSg5n', models.CharField(max_length=100)),
                ('compSg6n', models.CharField(max_length=100)),
                ('compPl1n', models.CharField(max_length=100)),
                ('compPl2n', models.CharField(max_length=100)),
                ('compPl3n', models.CharField(max_length=100)),
                ('compPl4n', models.CharField(max_length=100)),
                ('compPl5n', models.CharField(max_length=100)),
                ('compPl6n', models.CharField(max_length=100)),
                ('supSg1m', models.CharField(max_length=100)),
                ('supSg2m', models.CharField(max_length=100)),
                ('supSg3m', models.CharField(max_length=100)),
                ('supSg4m', models.CharField(max_length=100)),
                ('supSg5m', models.CharField(max_length=100)),
                ('supSg6m', models.CharField(max_length=100)),
                ('supPl1m', models.CharField(max_length=100)),
                ('supPl2m', models.CharField(max_length=100)),
                ('supPl3m', models.CharField(max_length=100)),
                ('supPl4m', models.CharField(max_length=100)),
                ('supPl5m', models.CharField(max_length=100)),
                ('supPl6m', models.CharField(max_length=100)),
                ('supSg1f', models.CharField(max_length=100)),
                ('supSg2f', models.CharField(max_length=100)),
                ('supSg3f', models.CharField(max_length=100)),
                ('supSg4f', models.CharField(max_length=100)),
                ('supSg5f', models.CharField(max_length=100)),
                ('supSg6f', models.CharField(max_length=100)),
                ('supPl1f', models.CharField(max_length=100)),
                ('supPl2f', models.CharField(max_length=100)),
                ('supPl3f', models.CharField(max_length=100)),
                ('supPl4f', models.CharField(max_length=100)),
                ('supPl5f', models.CharField(max_length=100)),
                ('supPl6f', models.CharField(max_length=100)),
                ('supSg1n', models.CharField(max_length=100)),
                ('supSg2n', models.CharField(max_length=100)),
                ('supSg3n', models.CharField(max_length=100)),
                ('supSg4n', models.CharField(max_length=100)),
                ('supSg5n', models.CharField(max_length=100)),
                ('supSg6n', models.CharField(max_length=100)),
                ('supPl1n', models.CharField(max_length=100)),
                ('supPl2n', models.CharField(max_length=100)),
                ('supPl3n', models.CharField(max_length=100)),
                ('supPl4n', models.CharField(max_length=100)),
                ('supPl5n', models.CharField(max_length=100)),
                ('supPl6n', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='pl1',
            new_name='pl1f',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='pl2',
            new_name='pl1m',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='pl3',
            new_name='pl1n',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='pl4',
            new_name='pl2f',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='pl5',
            new_name='pl2m',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='pl6',
            new_name='pl2n',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='sg1',
            new_name='pl3f',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='sg2',
            new_name='pl3m',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='sg3',
            new_name='pl3n',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='sg4',
            new_name='pl4f',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='sg5',
            new_name='pl4m',
        ),
        migrations.RenameField(
            model_name='declination',
            old_name='sg6',
            new_name='pl4n',
        ),
        migrations.AddField(
            model_name='declination',
            name='pl5f',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='pl5m',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='pl5n',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='pl6f',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='pl6m',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='pl6n',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg1f',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg1m',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg1n',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg2f',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg2m',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg2n',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg3f',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg3m',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg3n',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg4f',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg4m',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg4n',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg5f',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg5m',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg5n',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg6f',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg6m',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declination',
            name='sg6n',
            field=models.CharField(max_length=12, default=''),
            preserve_default=False,
        ),
    ]
